### ISSUE TITLE
Space issues -- when a pod is full -- gitpuller fails

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#205]
When a pod is at the 10gb capacity -- gitpuller fails.
This is making me realize that pods could fill up simply because of git history .git files getting large. So we may need to consider the user of gitpuller OR at a minimum launch is via a try catch so a pod can still load. if gitpuller fails, it can continue to launch the pod regardless and fail gracefully. right now my pod - lwasser is totally full and thus it's failing. 
```
2020-05-07 14:45:39+00:00 [Warning] Exec lifecycle hook ([sh -c gitpuller https://github.com/earthlab-education/spring-2020-course-notebooks master ea-2020-class-notebooks; ]) for Container "notebook" in Pod "jupyter-lwasser_ea-hub(4c84301e-9071-11ea-97b9-42010a800008)" failed - error: command 'sh -c gitpuller https://github.com/earthlab-education/spring-2020-course-notebooks master ea-2020-class-notebooks; ' exited with 1: Traceback (most recent call last): File "/opt/conda/bin/gitpuller", line 10, in <module> sys.exit(main()) File "/opt/conda/lib/python3.7/site-packages/nbgitpuller/pull.py", line 251, in main args.repo_dir File "/opt/conda/lib/python3.7/site-packages/nbgitpuller/pull.py", line 81, in pull yield from self.update() File "/opt/conda/lib/python3.7/site-packages/nbgitpuller/pull.py", line 191, in update yield from self.update_remotes() File "/opt/conda/lib/python3.7/site-packages/nbgitpuller/pull.py", line 128, in update_remotes yield from execute_cmd(['git', 'fetch'], cwd=self.repo_dir) File "/opt/conda/lib/python3.7/site-packages/nbgitpuller/pull.py", line 43, in execute_cmd raise subprocess.CalledProcessError(ret, cmd) subprocess.CalledProcessError: Command '['git', 'fetch']' returned non-zero exit status 128. , message: "$ git fetch\n\nerror: unable to create temporary file: No space left on device\n\nfatal: failed to write object\n\nfatal: unpack-objects failed\n\nTraceback (most recent call last):\n File \"/opt/conda/bin/gitpuller\", line 10, in <module>\n sys.exit(main())\n File \"/opt/conda/lib/python3.7/site-packages/nbgitpuller/pull.py\", line 251, in main\n args.repo_dir\n File \"/opt/conda/lib/python3.7/site-packages/nbgitpuller/pull.py\", line 81, in pull\n yield from self.update()\n File \"/opt/conda/lib/python3.7/site-packages/nbgitpuller/pull.py\", line 191, in update\n yield from self.update_remotes()\n File \"/opt/conda/lib/python3.7/site-packages/nbgitpuller/pull.py\", line 128, in update_remotes\n yield from execute_cmd(['git', 'fetch'], cwd=self.repo_dir)\n File \"/opt/conda/lib/python3.7/site-packages/nbgitpuller/pull.py\", line 43, in execute_cmd\n raise subprocess.CalledProcessError(ret, cmd)\nsubprocess.CalledProcessError: Command '['git', 'fetch']' returned non-zero exit status 128.\n"

```

**Comment by kcranston** [comment]
Might be worth looking into the [depth option](https://jupyterhub.github.io/nbgitpuller/topic/url-options.html#depth) for nbgitpuller.

**Comment by lwasser** [comment]
yes!! that is what i was looking for! we don't need the entire history - just the files.

**Comment by lwasser** [comment]
so resolution: 
## ADD TO DOCS: 
if a pod is full we can resize and have the students download all data and clean stuff up

`df -h` to get a list of capacity / available storage (`jovyan/`)

## ADD TO BUILD
use `gitpuller` in `scarce` mode via the depth option (if we think it will work consistently)

**Comment by lwasser** [comment]
@kcranston @nkorinek just noting that we have this issue again. when a pod is full (i'll confirm this shortly) the hub won't launch. i think we need to look into a way to avoid this issue. it should fail gracefully and if an upload is too large it should somehow provide a message .

**Comment by lwasser** [comment]
how do i check the capacity left on a pod that won't launch? below i can see that the storage capacity can be checked in jupyter but if the pod won't launch this doesn't work. i want to see if a pod is full

https://earthlab-hub-ops.readthedocs.io/en/latest/daily-operations/manage-storage.html#check-pod-storage-capacity

**Comment by kcranston** [comment]
Thanks for the note. I have a local branch where I started looking into how to wrap that nbgitpuller command in a script with proper error handling. I'll resurrect that. 

As far as checking capacity, you can log into a pod and then use standard bash commands, e.g.:

`$ kubectl -n staginghub exec -it jupyter-kcranston bash`

then, when logged in: 

`jovyan@jupyter-kcranston:~$ du -h`
