### ISSUE TITLE
git puller quirk / fail

### ISSUE THREAD

**Issue by lwasser** [earthlab/hub-ops#298]
gitpuller is now killing the climate hub

I did create the repo to pull from and it does NOT have an actual notebook in it but i would  think it would work regardless as there is a readme. i will add an empty notebook to see if that helps.

```
2020-10-28 15:06:31+00:00 [Warning] Exec lifecycle hook ([sh -c gitpuller https://github.com/earthlab/climate-data-101; ]) for Container "notebook" in Pod "jupyter-lwasser_climate-hub(1db2e779-192f-11eb-bca4-42010a8000dd)" failed - error: command 'sh -c gitpuller https://github.com/earthlab/climate-data-101; ' exited with 1: Traceback (most recent call last): File "/opt/conda/bin/gitpuller", line 10, in <module> sys.exit(main()) File "/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py", line 250, in main for line in GitPuller( File "/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py", line 86, in pull yield from self.update() File "/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py", line 194, in update yield from self.update_remotes() File "/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py", line 132, in update_remotes yield from execute_cmd(['git', 'fetch'], cwd=self.repo_dir) File "/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py", line 45, in execute_cmd raise subprocess.CalledProcessError(ret, cmd) subprocess.CalledProcessError: Command '['git', 'fetch']' returned non-zero exit status 128. , message: "$ git fetch\n\nfatal: not a git repository (or any parent up to mount point /home)\n\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n\nTraceback (most recent call last):\n File \"/opt/conda/bin/gitpuller\", line 10, in <module>\n sys.exit(main())\n File \"/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py\", line 250, in main\n for line in GitPuller(\n File \"/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py\", line 86, in pull\n yield from self.update()\n File \"/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py\", line 194, in update\n yield from self.update_remotes()\n File \"/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py\", line 132, in update_remotes\n yield from execute_cmd(['git', 'fetch'], cwd=self.repo_dir)\n File \"/opt/conda/lib/python3.8/site-packages/nbgitpuller/pull.py\", line 45, in execute_cmd\n raise subprocess.CalledProcessError(ret, cmd)\nsubprocess.CalledProcessError: Command '['git', 'fetch']' returned non-zero exit status 128.\n"
```

**Comment by lwasser** [comment]
Update - i did notice that there was a mistake in how gitpuller was called (no branch or dirname specified) ... lesson learned to use an existing quarter implemented PR ... so testing now if the issue is that simple or something bigger.

**Comment by lwasser** [comment]
ok there were two fixes.
1. the original PR #296  had a wrong values which caused failed build. i shouldn't have used it as a base
2. the gitpuller call was calling a valid repo but github moved away from master to main! YES this is good but i didn't know it happened so it was trying to call the master brain when only main existed. 

both are fixed and i was able to login so i'll close this
